// Generated by scripts/build_assessment_index.py. Do not edit by hand.
export const assessmentIndex = {
  "generatedAt": "2026-07-06T05:35:04.335352+00:00",
  "rootLabel": "Local AI Programming source tree",
  "scannedSourceCount": 200,
  "indexedSourceCount": 49,
  "skippedSourceCount": 0,
  "defaultSourceId": "src-057-unit-2-git-ac2-3-commit-version-control-evidence-ac2-3-submission-pack",
  "sources": [
    {
      "id": "src-012-l3-certificate-in-ai-programming-with-python-unit-3-assessment-3-numpy",
      "title": "SS Evidence Collection Learner Unit 3 Assessment 3 OG Web.site Branded",
      "unit": "Unit-3",
      "path": "L3-Certificate-in-AI-Programming-with-Python/unit-3/assessment-3-numpy-ndarray-evidence/SS Evidence Collection Learner Unit 3 Assessment 3 - OG Web.site Branded.docx",
      "type": "docx",
      "criteriaText": "4.1 Create an ndarray using NumPy.\n4.3 Save an ndarray using NumPy.\n3.3 Explain the process using comments or markdown cells in Jupyter Notebook.",
      "criteriaCount": 3,
      "keywords": [
        "3.3",
        "4.1",
        "4.3"
      ]
    },
    {
      "id": "src-017-l3-certificate-in-ai-programming-with-python-unit-3-assessment-4-panda",
      "title": "SS Evidence Collection Learner Unit 3 Assessment 4 OG Web.site Branded",
      "unit": "Unit-3",
      "path": "L3-Certificate-in-AI-Programming-with-Python/unit-3/assessment-4-pandas-evidence/SS Evidence Collection Learner Unit 3 Assessment 4 - OG Web.site Branded.docx",
      "type": "docx",
      "criteriaText": "4.3 Create, access and delete elements in Pandas Series and DataFrames.",
      "criteriaCount": 1,
      "keywords": [
        "4.3"
      ]
    },
    {
      "id": "src-033-l3-certificate-in-ai-programming-with-python-unit-4-assessment-3-vecto",
      "title": "Unit 4 Assessment 3 Evidence Collection Learner",
      "unit": "Unit-4",
      "path": "L3-Certificate-in-AI-Programming-with-Python/unit-4/assessment-3-vectors/Unit 4 Assessment 3 - Evidence Collection - Learner.docx",
      "type": "docx",
      "criteriaText": "1.1 | Outline what a vector is. | Written answer explains vectors as ordered values; Python output creates [3, 4] and a feature vector with shape evidence.\n1.2 | Describe the purpose of vector transpose. | Python output shows a row vector shape (1, 3) transposed into a column vector shape (3, 1).\n1.3 | Outline how to calculate magnitude and direction. | Python output calculates magnitude with np.linalg.norm, angle with atan2, degrees, and unit vector.\n1.4 | Explain the use of vector additions and vector multiplication. | Q4 evidence shows feature adjustment addition, bias addition, element-wise multiplication and dot product score.\n1.5 | Describe how vectors support programming with Python. | Source file and notebook show NumPy arrays, shape checks, vectorised operations and AI-style feature vectors.",
      "criteriaCount": 5,
      "keywords": [
        "1.1",
        "1.2",
        "1.3",
        "1.4",
        "1.5"
      ]
    },
    {
      "id": "src-044-l3-certificate-in-ai-programming-with-python-unit-4-assessment-5-deep-",
      "title": "Unit 4 Assessment 5 SS Evidence Collection Learner",
      "unit": "Unit-4",
      "path": "L3-Certificate-in-AI-Programming-with-Python/unit-4/assessment-5-deep-learning-training-project/Unit 4 Assessment 5 - SS Evidence Collection - Learner.docx",
      "type": "docx",
      "criteriaText": "3.1 Demonstrate ways to train a deep learning model.\n3.2 Demonstrate the use of a validation set for hyperparameter tuning.\n3.3 Demonstrate how to use deep learning for inference.",
      "criteriaCount": 3,
      "keywords": [
        "3.1",
        "3.2",
        "3.3"
      ]
    },
    {
      "id": "src-045-l3-certificate-in-ai-programming-with-python-unit-4-assessment-5-deep-",
      "title": "Unit 4 Assessment 5 TQUK Observation Record Learner",
      "unit": "Unit-4",
      "path": "L3-Certificate-in-AI-Programming-with-Python/unit-4/assessment-5-deep-learning-training-project/Unit 4 Assessment 5 - TQUK Observation Record - Learner.docx",
      "type": "docx",
      "criteriaText": "3.1 Demonstrate ways to train a deep learning model. | Two Iris training routes are supplied: Method 1 baseline training and Method 2 validation-based training. |\n3.2 Demonstrate the use of a validation set for hyperparameter tuning. | Method 2 compares hidden-size and learning-rate configurations using a validation set before final testing. |\n3.3 Demonstrate how to use deep learning for inference. | Method 2 uses the selected trained network to predict a held-back Iris sample and records probabilities. |",
      "criteriaCount": 3,
      "keywords": [
        "3.1",
        "3.2",
        "3.3"
      ]
    },
    {
      "id": "src-047-l3-certificate-in-ai-programming-with-python-unit-4-assessment-6-pretr",
      "title": "Unit 4 Assessment 6 SS Evidence Collection Learner",
      "unit": "Unit-4",
      "path": "L3-Certificate-in-AI-Programming-with-Python/unit-4/assessment-6-pretrained-networks-and-image-processing-project/01 Evidence Collection/Unit 4 Assessment 6 - SS Evidence Collection - Learner.docx",
      "type": "docx",
      "criteriaText": "3.3 Inference using random scaling, rotation, mirroring and cropping.\n4.1 Use of pre-trained networks.\n4.2 Training script utilises the GPU.\n4.3 Image processing.\n4.7 Save the model and load checkpoints.",
      "criteriaCount": 5,
      "keywords": [
        "3.3",
        "4.1",
        "4.2",
        "4.3",
        "4.7"
      ]
    },
    {
      "id": "src-052-ss-evidence-collection-learner-ai-programming-og-website-branded-docx",
      "title": "SS Evidence Collection Learner Ai Programming OG Website Branded",
      "unit": "AI Programming",
      "path": "SS_Evidence_Collection_Learner_Ai_Programming_OG_Website_Branded.docx",
      "type": "docx",
      "criteriaText": "2.1 Create a GitHub repository\n2.2 Create a fork GitHub repository\n2.3 Use descriptive commit messages\n2.3 Use commits to refactor",
      "criteriaCount": 4,
      "keywords": [
        "2.1",
        "2.2",
        "2.3"
      ]
    },
    {
      "id": "src-055-unit-1-assessment-2-file-index-txt",
      "title": "File index",
      "unit": "Unit 1",
      "path": "Unit 1/assessment 2/File index.txt",
      "type": "txt",
      "criteriaText": "2.1 Implement decision-making in code:\n2.2 Demonstrate the use of built-in functions:\n2.3 Demonstrate the use of loops:\n3.1 Demonstrate the use of functions:\n4.1 Write and run Python scripts:\n4.3 Demonstrate the use of modules within the script:",
      "criteriaCount": 6,
      "keywords": [
        "2.1",
        "2.2",
        "2.3",
        "3.1",
        "4.1",
        "4.3"
      ]
    },
    {
      "id": "src-057-unit-2-git-ac2-3-commit-version-control-evidence-ac2-3-submission-pack",
      "title": "AC2.3 SS Evidence Collection Learner",
      "unit": "Unit 2 Git",
      "path": "Unit 2 Git/AC2.3 Commit Version Control Evidence/AC2.3 Submission Pack - Learner/01 Evidence Collection/AC2.3 SS Evidence Collection - Learner.docx",
      "type": "docx",
      "criteriaText": "AC2.3 - Create descriptive commits with clear commit messages.\nAC2.3 - Show commit history using git log --oneline after the work.\nAC2.3 - Refactor code without changing its purpose and commit the refactor.\nAC2.3 - Push commits to the correct OG-Website GitHub remote repository and verify the remote branch.",
      "criteriaCount": 4,
      "keywords": [
        "AC2.3"
      ]
    },
    {
      "id": "src-060-unit-2-git-ai-programming-github-assessment-full-step-by-step-guide-do",
      "title": "Ai Programming GitHub Assessment FULL Step by Step Guide",
      "unit": "Unit 2 Git",
      "path": "Unit 2 Git/Ai-Programming_GitHub_Assessment_FULL_Step_by_Step_Guide.docx",
      "type": "docx",
      "criteriaText": "2.1 Create a GitHub repository\n2.2 Create a fork GitHub repository\n2.3 Use commits to refactor - Ali example web section before terminal\n2.1 Create a GitHub repository | 1-3\n2.2 Create a fork GitHub repository | 4-6\n2.3 Use descriptive commit messages | 3, 9, 12, 17\n2.3 Use commits to refactor | 7-10",
      "criteriaCount": 7,
      "keywords": [
        "2.1",
        "2.2",
        "2.3"
      ]
    },
    {
      "id": "src-061-unit-2-git-ai-programming-github-assessment-step-by-step-guide-docx",
      "title": "Ai Programming GitHub Assessment Step by Step Guide",
      "unit": "Unit 2 Git",
      "path": "Unit 2 Git/Ai-Programming_GitHub_Assessment_Step_by_Step_Guide.docx",
      "type": "docx",
      "criteriaText": "AC 2.1 Create a GitHub repository\nAC 2.2 Create a fork GitHub repository\nAC 2.3 Demonstrate commits: first descriptive commit\nAC 2.3 Use commits to refactor",
      "criteriaCount": 4,
      "keywords": [
        "AC 2.1",
        "AC 2.2",
        "AC 2.3"
      ]
    },
    {
      "id": "src-062-unit-2-git-assessment-3-assessment-3-og-web-site-submission-pack-01-ev",
      "title": "SS Evidence Collection Learner Unit 2 Assessment 3",
      "unit": "Unit 2 Git",
      "path": "Unit 2 Git/Assessment 3/Assessment 3 - OG Web.site Submission Pack/01 Evidence Collection/SS Evidence Collection Learner Unit 2 Assessment 3.docx",
      "type": "docx",
      "criteriaText": "2.4 Demonstrate how to mark files as untracked in GitHub.\n4.1 Demonstrate how to organise commits with tags and branches using GitHub.\n4.2 Demonstrate how to check branches have changed in GitHub.\n4.3 Demonstrate how to merge branches using GitHub.",
      "criteriaCount": 4,
      "keywords": [
        "2.4",
        "4.1",
        "4.2",
        "4.3"
      ]
    },
    {
      "id": "src-063-unit-2-git-assessment-3-assessment-3-og-web-site-submission-pack-01-ev",
      "title": "SS Evidence Collection Learner Unit 2 Assessment 3",
      "unit": "Unit 2 Git",
      "path": "Unit 2 Git/Assessment 3/Assessment 3 - OG Web.site Submission Pack/01 Evidence Collection/SS Evidence Collection Learner Unit 2 Assessment 3.pdf",
      "type": "pdf",
      "criteriaText": "\u2022 2.4 Demonstrate how to mark files as untracked in GitHub.\n\u2022 4.1 Demonstrate how to organise commits with tags and branches using GitHub.\n\u2022 4.2 Demonstrate how to check branches have changed in GitHub.\n\u2022 4.3 Demonstrate how to merge branches using GitHub.\n2.4 - Create new file page\n4.1 - Create file on assessment\n4.1 - Create new release page\n4.1 - Create New Tag\n4.3 - Confirm merge message\n4.3 - Main branch after merge",
      "criteriaCount": 10,
      "keywords": [
        "2.4",
        "4.1",
        "4.2",
        "4.3"
      ]
    },
    {
      "id": "src-064-unit-2-git-assessment-3-assessment-3-og-web-site-submission-pack-02-gi",
      "title": "SS GitHub How To Guides Learner Unit 2 Assessment 3",
      "unit": "Unit 2 Git",
      "path": "Unit 2 Git/Assessment 3/Assessment 3 - OG Web.site Submission Pack/02 GitHub How To Guides/SS GitHub How To Guides Learner Unit 2 Assessment 3.docx",
      "type": "docx",
      "criteriaText": "2.4 Mark files as untracked in GitHub\n4.1 Organise commits with branches and tags in GitHub\n4.2 Check branch changes in GitHub\n4.3 Merge branches in GitHub",
      "criteriaCount": 4,
      "keywords": [
        "2.4",
        "4.1",
        "4.2",
        "4.3"
      ]
    },
    {
      "id": "src-065-unit-2-git-assessment-3-assessment-3-og-web-site-submission-pack-02-gi",
      "title": "SS GitHub How To Guides Learner Unit 2 Assessment 3",
      "unit": "Unit 2 Git",
      "path": "Unit 2 Git/Assessment 3/Assessment 3 - OG Web.site Submission Pack/02 GitHub How To Guides/SS GitHub How To Guides Learner Unit 2 Assessment 3.pdf",
      "type": "pdf",
      "criteriaText": "2.4 Mark files as untracked in GitHub\n4.1 Organise commits with branches and tags in GitHub\n4.2 Check branch changes in GitHub\n4.3 Merge branches in GitHub",
      "criteriaCount": 4,
      "keywords": [
        "2.4",
        "4.1",
        "4.2",
        "4.3"
      ]
    },
    {
      "id": "src-066-unit-2-git-assessment-3-assessment-3-og-web-site-submission-pack-04-we",
      "title": "Assessment 3 Index Learner",
      "unit": "Unit 2 Git",
      "path": "Unit 2 Git/Assessment 3/Assessment 3 - OG Web.site Submission Pack/04 Website and URL Evidence/Assessment 3 Index - Learner.txt",
      "type": "txt",
      "criteriaText": "2.4 Mark files as untracked in GitHub video\n4.1 Organise commits with branches and tags in GitHub video\n4.2 Check branches have changed in GitHub video\n4.3 Merge branches using GitHub video",
      "criteriaCount": 4,
      "keywords": [
        "2.4",
        "4.1",
        "4.2",
        "4.3"
      ]
    },
    {
      "id": "src-070-unit-2-git-assessment-3-assessment-3-og-web-site-submission-pack-file-",
      "title": "File Index Assessment 3 OG Web.site",
      "unit": "Unit 2 Git",
      "path": "Unit 2 Git/Assessment 3/Assessment 3 - OG Web.site Submission Pack/File Index - Assessment 3 OG Web.site.txt",
      "type": "txt",
      "criteriaText": "2.4 mark files as untracked\n4.1 organise commits with tags and branches\n4.2 check branches have changed\n4.3 merge branches",
      "criteriaCount": 4,
      "keywords": [
        "2.4",
        "4.1",
        "4.2",
        "4.3"
      ]
    },
    {
      "id": "src-071-unit-2-git-assessment-3-assessment-3-answer-text-learner-txt",
      "title": "Assessment 3 Answer Text Learner",
      "unit": "Unit 2 Git",
      "path": "Unit 2 Git/Assessment 3/Assessment 3 Answer Text - Learner.txt",
      "type": "txt",
      "criteriaText": "2.4 Mark files as untracked in GitHub video\n4.1 Organise commits with branches and tags in GitHub video\n4.2 Check branches have changed in GitHub video\n4.3 Merge branches using GitHub video",
      "criteriaCount": 4,
      "keywords": [
        "2.4",
        "4.1",
        "4.2",
        "4.3"
      ]
    },
    {
      "id": "src-072-unit-2-git-assessment-3-assessment-3-github-how-to-guides-learner-1-do",
      "title": "Assessment 3 GitHub How To Guides Learner (1)",
      "unit": "Unit 2 Git",
      "path": "Unit 2 Git/Assessment 3/Assessment_3_GitHub_How_To_Guides_Learner (1).docx",
      "type": "docx",
      "criteriaText": "2.4 Demonstrate how to mark files as untracked in GitHub.\n4.1 Demonstrate how to organise commits with tags and branches using GitHub.\n4.2 Demonstrate how to check branches have changed in GitHub.\n4.3 Demonstrate how to merge branches using GitHub.",
      "criteriaCount": 4,
      "keywords": [
        "2.4",
        "4.1",
        "4.2",
        "4.3"
      ]
    },
    {
      "id": "src-073-unit-2-git-assessment-3-assessment-3-github-organisation-full-step-by-",
      "title": "Assessment 3 GitHub Organisation FULL Step by Step Guide Learner",
      "unit": "Unit 2 Git",
      "path": "Unit 2 Git/Assessment 3/Assessment_3_GitHub_Organisation_FULL_Step_by_Step_Guide_Learner.docx",
      "type": "docx",
      "criteriaText": "2.4 | How to mark files as untracked | 1-5\n4.1 | How to organise commits with tags and branches | 6-12\n4.2 | How to check branches have changed | 13-16\n4.3 | How to merge branches | 17-22",
      "criteriaCount": 4,
      "keywords": [
        "2.4",
        "4.1",
        "4.2",
        "4.3"
      ]
    },
    {
      "id": "src-074-unit-2-git-assessment-3-ss-evidence-collection-learner-unit-2-assessme",
      "title": "SS Evidence Collection Learner Unit 2 Assessment 2 BEFORE GitHub URLs backup",
      "unit": "Unit 2 Git",
      "path": "Unit 2 Git/Assessment 3/SS Evidence Collection Learner Unit 2 Assessment 2 - BEFORE GitHub URLs backup.docx",
      "type": "docx",
      "criteriaText": "2.1 Create a GitHub repository.\n2.2 Create a fork GitHub repository.\n2.3 Use descriptive commit messages\n2.3 Use commits to refactor.",
      "criteriaCount": 4,
      "keywords": [
        "2.1",
        "2.2",
        "2.3"
      ]
    },
    {
      "id": "src-075-unit-2-git-assessment-3-ss-evidence-collection-learner-unit-2-assessme",
      "title": "SS Evidence Collection Learner Unit 2 Assessment 2 GitHub URLs Added",
      "unit": "Unit 2 Git",
      "path": "Unit 2 Git/Assessment 3/SS Evidence Collection Learner Unit 2 Assessment 2 - GitHub URLs Added.docx",
      "type": "docx",
      "criteriaText": "2.1 Create a GitHub repository.\n2.2 Create a fork GitHub repository.\n2.3 Use descriptive commit messages\n2.3 Use commits to refactor.",
      "criteriaCount": 4,
      "keywords": [
        "2.1",
        "2.2",
        "2.3"
      ]
    },
    {
      "id": "src-076-unit-2-git-assessment-3-ss-evidence-collection-learner-unit-2-assessme",
      "title": "SS Evidence Collection Learner Unit 2 Assessment 2",
      "unit": "Unit 2 Git",
      "path": "Unit 2 Git/Assessment 3/SS Evidence Collection Learner Unit 2 Assessment 2.docx",
      "type": "docx",
      "criteriaText": "2.1 Create a GitHub repository.\n2.2 Create a fork GitHub repository.\n2.3 Use descriptive commit messages\n2.3 Use commits to refactor.",
      "criteriaCount": 4,
      "keywords": [
        "2.1",
        "2.2",
        "2.3"
      ]
    },
    {
      "id": "src-077-unit-2-git-assessment-3-ss-evidence-collection-learner-unit-2-assessme",
      "title": "SS Evidence Collection Learner Unit 2 Assessment 2",
      "unit": "Unit 2 Git",
      "path": "Unit 2 Git/Assessment 3/SS Evidence Collection Learner Unit 2 Assessment 2.pdf",
      "type": "pdf",
      "criteriaText": "\u2022 2.1 Create a GitHub repository\n\u2022 2.2 Create a fork GitHub repository\n\u2022 2.3 Use descriptive commit messages\n\u2022 2.3 Use commits to refactor",
      "criteriaCount": 4,
      "keywords": [
        "2.1",
        "2.2",
        "2.3"
      ]
    },
    {
      "id": "src-078-unit-2-git-assessment-3-ss-evidence-collection-learner-unit-2-assessme",
      "title": "SS Evidence Collection Learner Unit 2 Assessment 3",
      "unit": "Unit 2 Git",
      "path": "Unit 2 Git/Assessment 3/SS Evidence Collection Learner Unit 2 Assessment 3.docx",
      "type": "docx",
      "criteriaText": "2.4 Demonstrate how to mark files as untracked in GitHub.\n4.1 Demonstrate how to organise commits with tags and branches using GitHub.\n4.2 Demonstrate how to check branches have changed in GitHub.\n4.3 Demonstrate how to merge branches using GitHub.",
      "criteriaCount": 4,
      "keywords": [
        "2.4",
        "4.1",
        "4.2",
        "4.3"
      ]
    },
    {
      "id": "src-079-unit-2-git-assessment-3-ss-evidence-collection-learner-unit-2-assessme",
      "title": "SS Evidence Collection Learner Unit 2 Assessment 3",
      "unit": "Unit 2 Git",
      "path": "Unit 2 Git/Assessment 3/SS Evidence Collection Learner Unit 2 Assessment 3.pdf",
      "type": "pdf",
      "criteriaText": "\u2022 2.4 Demonstrate how to mark files as untracked in GitHub.\n\u2022 4.1 Demonstrate how to organise commits with tags and branches using GitHub.\n\u2022 4.2 Demonstrate how to check branches have changed in GitHub.\n\u2022 4.3 Demonstrate how to merge branches using GitHub.\n2.4 - Create new file page\n4.1 - Create file on assessment\n4.1 - Create new release page\n4.1 - Create New Tag\n4.3 - Confirm merge message\n4.3 - Main branch after merge",
      "criteriaCount": 10,
      "keywords": [
        "2.4",
        "4.1",
        "4.2",
        "4.3"
      ]
    },
    {
      "id": "src-080-unit-2-git-assessment-3-ss-github-how-to-guides-learner-unit-2-assessm",
      "title": "SS GitHub How To Guides Learner Unit 2 Assessment 3",
      "unit": "Unit 2 Git",
      "path": "Unit 2 Git/Assessment 3/SS GitHub How To Guides Learner Unit 2 Assessment 3.docx",
      "type": "docx",
      "criteriaText": "2.4 Mark files as untracked in GitHub\n4.1 Organise commits with branches and tags in GitHub\n4.2 Check branch changes in GitHub\n4.3 Merge branches in GitHub",
      "criteriaCount": 4,
      "keywords": [
        "2.4",
        "4.1",
        "4.2",
        "4.3"
      ]
    },
    {
      "id": "src-081-unit-2-git-assessment-3-ss-github-how-to-guides-learner-unit-2-assessm",
      "title": "SS GitHub How To Guides Learner Unit 2 Assessment 3",
      "unit": "Unit 2 Git",
      "path": "Unit 2 Git/Assessment 3/SS GitHub How To Guides Learner Unit 2 Assessment 3.pdf",
      "type": "pdf",
      "criteriaText": "2.4 Mark files as untracked in GitHub\n4.1 Organise commits with branches and tags in GitHub\n4.2 Check branch changes in GitHub\n4.3 Merge branches in GitHub",
      "criteriaCount": 4,
      "keywords": [
        "2.4",
        "4.1",
        "4.2",
        "4.3"
      ]
    },
    {
      "id": "src-082-unit-2-git-assessment-3-what-to-do-txt",
      "title": "what to do",
      "unit": "Unit 2 Git",
      "path": "Unit 2 Git/Assessment 3/what to do.txt",
      "type": "txt",
      "criteriaText": "AC 2.4 Demonstrate how to mark files as untracked in GitHub.\nAC 4.1 Demonstrate how to organise commits with tags and branches using GitHub.\nAC 4.2 Demonstrate how to check branches have changed in GitHub.\nAC 4.3 Demonstrate how to merge branches using GitHub.",
      "criteriaCount": 4,
      "keywords": [
        "AC 2.4",
        "AC 4.1",
        "AC 4.2",
        "AC 4.3"
      ]
    },
    {
      "id": "src-099-unit-2-git-resources-20260615-assessment-support-documents-tquk-observ",
      "title": "TQUK Observation Record for 2.1, 2.2, 2.3, 3.1, 3.2, 3.3",
      "unit": "Unit 2 Git",
      "path": "Unit 2 Git/Resources...-20260615/Assessment Support Documents/TQUK Observation Record for 2.1, 2.2, 2.3, 3.1, 3.2, 3.3.docx",
      "type": "docx",
      "criteriaText": "2.1 Create a GitHub repository\n2.2 Create a fork GitHub repository\n2.3 Demonstrate the use of commits for version control. Learners must: Use commit descriptive messages Use commits to refactor Push commits to a remote repository Edit and delete commits\n3.1 Demonstrate how to verify a remote using GitHub.\n3.2 Demonstrate how to clone remote repositories using GitHub.\n3.3 Demonstrate how to push files to own remote repository using GitHub | Assessment criteria\n3.3 Demonstrate how to push files to own remote repository using GitHub | Date(s) Observed | Date(s) Observed\n3.3 Demonstrate how to push files to own remote repository using GitHub Use commit descriptive messages Use commits to refactor Push commits to a remote repository\n3.3 Demonstrate how to push files to own remote repository using GitHub",
      "criteriaCount": 9,
      "keywords": [
        "2.1",
        "2.2",
        "2.3",
        "3.1",
        "3.2",
        "3.3"
      ]
    },
    {
      "id": "src-100-unit-2-git-resources-20260615-assessment-support-documents-tquk-observ",
      "title": "TQUK Observation Record for 2.4, 4.1, 4.2, 4.3",
      "unit": "Unit 2 Git",
      "path": "Unit 2 Git/Resources...-20260615/Assessment Support Documents/TQUK Observation Record for 2.4, 4.1, 4.2, 4.3.docx",
      "type": "docx",
      "criteriaText": "2.4 Demonstrate how to mark files as untracked in GitHub.\n4.1 Demonstrate how to organise commits with tags and branches using GitHub.\n4.2 Demonstrate how to check branches have changed in GitHub.\n4.3 Demonstrate how to merge branches using GitHub. | Assessment criteria\n4.3 Demonstrate how to merge branches using GitHub. | Date(s) Observed | Date(s) Observed\n4.3 Demonstrate how to merge branches using GitHub.",
      "criteriaCount": 6,
      "keywords": [
        "2.4",
        "4.1",
        "4.2",
        "4.3"
      ]
    },
    {
      "id": "src-102-unit-2-git-ss-evidence-collection-learner-ai-programming-docx",
      "title": "SS Evidence Collection Learner Ai Programming",
      "unit": "Unit 2 Git",
      "path": "Unit 2 Git/SS_Evidence_Collection_Learner_Ai_Programming.docx",
      "type": "docx",
      "criteriaText": "2.1 Create a GitHub repository\n2.2 Create a fork GitHub repository\n2.3 Use descriptive commit messages\n2.3 Use commits to refactor",
      "criteriaCount": 4,
      "keywords": [
        "2.1",
        "2.2",
        "2.3"
      ]
    },
    {
      "id": "src-104-unit-2-git-unit-2-l1-assessment-1-q1-txt",
      "title": "Unit 2 L1 Assessment 1 Q1",
      "unit": "Unit 2 Git",
      "path": "Unit 2 Git/Unit 2 L1 Assessment 1 Q1 .txt",
      "type": "txt",
      "criteriaText": "AC 1.1 \u2013 Outline why developers use version control",
      "criteriaCount": 1,
      "keywords": [
        "AC 1.1"
      ]
    },
    {
      "id": "src-105-unit-2-git-unit-2-l1-assessment-1-q2-txt",
      "title": "Unit 2 L1 Assessment 1 Q2",
      "unit": "Unit 2 Git",
      "path": "Unit 2 Git/Unit 2 L1 Assessment 1 Q2 .txt",
      "type": "txt",
      "criteriaText": "AC 1.2 \u2013 Explain ways to use version control",
      "criteriaCount": 1,
      "keywords": [
        "AC 1.2"
      ]
    },
    {
      "id": "src-106-unit-2-git-unit-2-l1-assessment-1-q3-txt",
      "title": "Unit 2 L1 Assessment 1 Q3",
      "unit": "Unit 2 Git",
      "path": "Unit 2 Git/Unit 2 L1 Assessment 1 Q3 .txt",
      "type": "txt",
      "criteriaText": "AC 3.4 \u2013 Describe the differences between fetch and pull",
      "criteriaCount": 1,
      "keywords": [
        "AC 3.4"
      ]
    },
    {
      "id": "src-109-unit-2-git-unit-2-github-for-python-l1-assessment-docx",
      "title": "Unit 2 \u2013 GitHub for Python L1 Assessment",
      "unit": "Unit 2 Git",
      "path": "Unit 2 Git/Unit 2 \u2013 GitHub for Python L1 Assessment.docx",
      "type": "docx",
      "criteriaText": "AC 1.1 \u2013 Outline why developers use version control\nAC 1.2 \u2013 Explain ways to use version control\nAC 3.4 \u2013 Describe the differences between fetch and pull",
      "criteriaCount": 3,
      "keywords": [
        "AC 1.1",
        "AC 1.2",
        "AC 3.4"
      ]
    },
    {
      "id": "src-121-unit-3-libraries-for-python-assessment-3-numpy-ndarray-evidence-ss-evi",
      "title": "SS Evidence Collection Learner Unit 3 Assessment 3 OG Web.site Branded",
      "unit": "Unit 3 - Libraries For Python",
      "path": "Unit 3 - Libraries for python/Assessment 3 - NumPy ndarray Evidence/SS Evidence Collection Learner Unit 3 Assessment 3 - OG Web.site Branded.docx",
      "type": "docx",
      "criteriaText": "4.1 Create an ndarray using NumPy.\n4.3 Save an ndarray using NumPy.\n3.3 Explain the process using comments or markdown cells in Jupyter Notebook.",
      "criteriaCount": 3,
      "keywords": [
        "3.3",
        "4.1",
        "4.3"
      ]
    },
    {
      "id": "src-126-unit-3-libraries-for-python-assessment-4-pandas-evidence-ss-evidence-c",
      "title": "SS Evidence Collection Learner Unit 3 Assessment 4 OG Web.site Branded",
      "unit": "Unit 3 - Libraries For Python",
      "path": "Unit 3 - Libraries for python/Assessment 4 - Pandas Evidence/SS Evidence Collection Learner Unit 3 Assessment 4 - OG Web.site Branded.docx",
      "type": "docx",
      "criteriaText": "4.3 Create, access and delete elements in Pandas Series and DataFrames.",
      "criteriaCount": 1,
      "keywords": [
        "4.3"
      ]
    },
    {
      "id": "src-164-unit-4-linear-algebra-essentials-for-deep-learning-assessment-3-vector",
      "title": "Unit 4 Assessment 3 Evidence Collection Learner",
      "unit": "Unit 4 - Linear Algebra Essentials For Deep Learning",
      "path": "Unit 4 - Linear Algebra Essentials for Deep Learning/Assessment 3 - Vectors/Assessment 3 - Upload Files/Unit 4 Assessment 3 - Evidence Collection - Learner.docx",
      "type": "docx",
      "criteriaText": "1.1 | Outline what a vector is. | Written answer explains vectors as ordered values; Python output creates [3, 4] and a feature vector with shape evidence.\n1.2 | Describe the purpose of vector transpose. | Python output shows a row vector shape (1, 3) transposed into a column vector shape (3, 1).\n1.3 | Outline how to calculate magnitude and direction. | Python output calculates magnitude with np.linalg.norm, angle with atan2, degrees, and unit vector.\n1.4 | Explain the use of vector additions and vector multiplication. | Q4 evidence shows feature adjustment addition, bias addition, element-wise multiplication and dot product score.\n1.5 | Describe how vectors support programming with Python. | Source file and notebook show NumPy arrays, shape checks, vectorised operations and AI-style feature vectors.",
      "criteriaCount": 5,
      "keywords": [
        "1.1",
        "1.2",
        "1.3",
        "1.4",
        "1.5"
      ]
    },
    {
      "id": "src-169-unit-4-linear-algebra-essentials-for-deep-learning-assessment-4-linear",
      "title": "Unit 4 Assessment 4 Answer Sheet with Embedded Images Learner",
      "unit": "Unit 4 - Linear Algebra Essentials For Deep Learning",
      "path": "Unit 4 - Linear Algebra Essentials for Deep Learning/Assessment 4 - Linear Algebra and Matrices/Assessment 4 - VLE Answer Sheet/Unit 4 Assessment 4 - Answer Sheet with Embedded Images - Learner.docx",
      "type": "docx",
      "criteriaText": "2.1 Provide examples of linear combination and linear span.\n2.2 Describe the use of linear dependency.\n3.1 Describe what is meant by a matrix.\n3.2 Apply matrix arithmetic for addition, scalar multiplication and multiplication.\n4.1 Explain how feedforward processing uses linear algebra.",
      "criteriaCount": 5,
      "keywords": [
        "2.1",
        "2.2",
        "3.1",
        "3.2",
        "4.1"
      ]
    },
    {
      "id": "src-170-unit-4-linear-algebra-essentials-for-deep-learning-assessment-4-linear",
      "title": "Unit 4 Assessment 4 Evidence Collection Learner",
      "unit": "Unit 4 - Linear Algebra Essentials For Deep Learning",
      "path": "Unit 4 - Linear Algebra Essentials for Deep Learning/Assessment 4 - Linear Algebra and Matrices/Unit 4 Assessment 4 - Evidence Collection - Learner.docx",
      "type": "docx",
      "criteriaText": "2.1 Provide examples of linear combination and linear span.\n2.2 Describe the use of linear dependency.\n3.1 Describe what is meant by a matrix.\n3.2 Apply matrix arithmetic for addition, scalar multiplication and multiplication.\n4.1 Explain how feedforward processing uses linear algebra.",
      "criteriaCount": 5,
      "keywords": [
        "2.1",
        "2.2",
        "3.1",
        "3.2",
        "4.1"
      ]
    },
    {
      "id": "src-174-unit-4-linear-algebra-essentials-for-deep-learning-assessment-5-deep-l",
      "title": "Unit 4 Assessment 5 SS Evidence Collection Learner",
      "unit": "Unit 4 - Linear Algebra Essentials For Deep Learning",
      "path": "Unit 4 - Linear Algebra Essentials for Deep Learning/Assessment 5 - Deep Learning Training Project/Unit 4 Assessment 5 - SS Evidence Collection - Learner.docx",
      "type": "docx",
      "criteriaText": "3.1 Demonstrate ways to train a deep learning model.\n3.2 Demonstrate the use of a validation set for hyperparameter tuning.\n3.3 Demonstrate how to use deep learning for inference.",
      "criteriaCount": 3,
      "keywords": [
        "3.1",
        "3.2",
        "3.3"
      ]
    },
    {
      "id": "src-178-unit-4-linear-algebra-essentials-for-deep-learning-assessment-5-deep-l",
      "title": "Unit 4 Assessment 5 SS Evidence Collection Learner",
      "unit": "Unit 4 - Linear Algebra Essentials For Deep Learning",
      "path": "Unit 4 - Linear Algebra Essentials for Deep Learning/Assessment 5 - Deep Learning Training Project/Unit 4 Assessment 5 - Submission Pack - Learner/01 Iris/Unit 4 Assessment 5 - SS Evidence Collection - Learner.docx",
      "type": "docx",
      "criteriaText": "3.1 Demonstrate ways to train a deep learning model.\n3.2 Demonstrate the use of a validation set for hyperparameter tuning.\n3.3 Demonstrate how to use deep learning for inference.",
      "criteriaCount": 3,
      "keywords": [
        "3.1",
        "3.2",
        "3.3"
      ]
    },
    {
      "id": "src-179-unit-4-linear-algebra-essentials-for-deep-learning-assessment-5-deep-l",
      "title": "Unit 4 Assessment 5 TQUK Observation Record Learner",
      "unit": "Unit 4 - Linear Algebra Essentials For Deep Learning",
      "path": "Unit 4 - Linear Algebra Essentials for Deep Learning/Assessment 5 - Deep Learning Training Project/Unit 4 Assessment 5 - Submission Pack - Learner/01 Iris/Unit 4 Assessment 5 - TQUK Observation Record - Learner.docx",
      "type": "docx",
      "criteriaText": "3.1 Demonstrate ways to train a deep learning model. | Two Iris training routes are supplied: Method 1 baseline training and Method 2 validation-based training. |\n3.2 Demonstrate the use of a validation set for hyperparameter tuning. | Method 2 compares hidden-size and learning-rate configurations using a validation set before final testing. |\n3.3 Demonstrate how to use deep learning for inference. | Method 2 uses the selected trained network to predict a held-back Iris sample and records probabilities. |",
      "criteriaCount": 3,
      "keywords": [
        "3.1",
        "3.2",
        "3.3"
      ]
    },
    {
      "id": "src-183-unit-4-linear-algebra-essentials-for-deep-learning-assessment-5-deep-l",
      "title": "Unit 4 Assessment 5 SS Evidence Collection Learner",
      "unit": "Unit 4 - Linear Algebra Essentials For Deep Learning",
      "path": "Unit 4 - Linear Algebra Essentials for Deep Learning/Assessment 5 - Deep Learning Training Project/Unit 4 Assessment 5 - Submission Pack - Learner/02 Trade/Unit 4 Assessment 5 - SS Evidence Collection - Learner.docx",
      "type": "docx",
      "criteriaText": "3.1 Demonstrate two ways to train a deep learning model.\n3.2 Demonstrate the use of a validation set for hyperparameter tuning.\n3.3 Demonstrate how to use deep learning for inference.",
      "criteriaCount": 3,
      "keywords": [
        "3.1",
        "3.2",
        "3.3"
      ]
    },
    {
      "id": "src-184-unit-4-linear-algebra-essentials-for-deep-learning-assessment-5-deep-l",
      "title": "Unit 4 Assessment 5 TQUK Observation Record Learner",
      "unit": "Unit 4 - Linear Algebra Essentials For Deep Learning",
      "path": "Unit 4 - Linear Algebra Essentials for Deep Learning/Assessment 5 - Deep Learning Training Project/Unit 4 Assessment 5 - TQUK Observation Record - Learner.docx",
      "type": "docx",
      "criteriaText": "3.1 Demonstrate ways to train a deep learning model. | Two Iris training routes are supplied: Method 1 baseline training and Method 2 validation-based training. |\n3.2 Demonstrate the use of a validation set for hyperparameter tuning. | Method 2 compares hidden-size and learning-rate configurations using a validation set before final testing. |\n3.3 Demonstrate how to use deep learning for inference. | Method 2 uses the selected trained network to predict a held-back Iris sample and records probabilities. |",
      "criteriaCount": 3,
      "keywords": [
        "3.1",
        "3.2",
        "3.3"
      ]
    },
    {
      "id": "src-186-unit-4-linear-algebra-essentials-for-deep-learning-assessment-6-pretra",
      "title": "Unit 4 Assessment 6 SS Evidence Collection Learner",
      "unit": "Unit 4 - Linear Algebra Essentials For Deep Learning",
      "path": "Unit 4 - Linear Algebra Essentials for Deep Learning/Assessment 6 - Pretrained Networks and Image Processing Project/01 Evidence Collection/Unit 4 Assessment 6 - SS Evidence Collection - Learner.docx",
      "type": "docx",
      "criteriaText": "3.3 Inference using random scaling, rotation, mirroring and cropping.\n4.1 Use of pre-trained networks.\n4.2 Training script utilises the GPU.\n4.3 Image processing.\n4.7 Save the model and load checkpoints.",
      "criteriaCount": 5,
      "keywords": [
        "3.3",
        "4.1",
        "4.2",
        "4.3",
        "4.7"
      ]
    },
    {
      "id": "src-190-unit-4-linear-algebra-essentials-for-deep-learning-assessments-criteri",
      "title": "assessments criteria",
      "unit": "Unit 4 - Linear Algebra Essentials For Deep Learning",
      "path": "Unit 4 - Linear Algebra Essentials for Deep Learning/assessments criteria .txt",
      "type": "txt",
      "criteriaText": "AC 1.1 Explain what \u2018deep learning' is.\nAC 1.2 Outline how calculus supports deep learning.\nAC 2.1 Explain what a derivative is and its purpose.\nAC 2.2 Outline the need for derivatives in deep learning.\nAC 2.1 Outline what gradient descent is.\nAC 2.2 Explain the importance of implementing gradient descent\nAC 2.3 Describe the benefits of gradient descent.\nAC 1.1 Explain the difference between testing and validation datasets.\nAC 1.2 Describe the purpose of validation loss and accuracy.\nAC 1.1 Outline what a \u2018vector\u2019 is.\nAC 1.2 Describe the purpose of vector transpose.\nAC 1.3 Outline how to calculate magnitude and direction.\nAC 1.4 Explain, the use of Vector additions. Vector multiplication.\nAC 1.5 Describe how vectors support programming with Python.\nAC 2.1 Give examples of Linear combination and Linear span.\nAC 2.2 Describe the use of linear dependency.\nAC 3.1 Outline what is meant by a \u2018matrix\u2019.\nAC 3.2 Explain how to apply matrix arithmetic to perform Matrix addition. Scalar multiplication of a matrix. Matrix multiplication.\nAC 4.1 Explain how the feedforward process uses linear algebra.\n3.1 Demonstrate ways to train the deep learning model\n3.2 Demonstrate the use of a validation set for hyperparameter tuning\n3.3 Demonstrate how to use deep learning for inference\n3.3 Demonstrate how to use deep learning for inference.\n4.1 Demonstrate the use of pre-trained networks.\n4.2 Create a training script that utilizes the GPU.\n4.3 Demonstrate the use of image processing.\n4.4 Demonstrate data normalisation.\n4.5 Demonstrate data augmentation.\n4.6 Demonstrate the use of data loading and data batching for training validation testing.\n4.7 Demonstrate how to save the model and load checkpoints.",
      "criteriaCount": 30,
      "keywords": [
        "3.1",
        "3.2",
        "3.3",
        "4.1",
        "4.2",
        "4.3",
        "4.4",
        "4.5",
        "4.6",
        "4.7",
        "AC 1.1",
        "AC 1.2",
        "AC 1.3",
        "AC 1.4",
        "AC 1.5",
        "AC 2.1",
        "AC 2.2",
        "AC 2.3",
        "AC 3.1",
        "AC 3.2",
        "AC 4.1"
      ]
    },
    {
      "id": "src-195-unit-4-linear-algebra-essentials-for-deep-learning-lesson-5-unit-4-ass",
      "title": "Unit 4 Assessment 5 SS Evidence Collection Learner",
      "unit": "Unit 4 - Linear Algebra Essentials For Deep Learning",
      "path": "Unit 4 - Linear Algebra Essentials for Deep Learning/lesson 5/Unit 4 Assessment 5 - SS Evidence Collection - Learner.docx",
      "type": "docx",
      "criteriaText": "3.1 Demonstrate two ways to train a deep learning model.\n3.2 Demonstrate the use of a validation set for hyperparameter tuning.\n3.3 Demonstrate how to use deep learning for inference.",
      "criteriaCount": 3,
      "keywords": [
        "3.1",
        "3.2",
        "3.3"
      ]
    }
  ]
};

export const assessmentSources = assessmentIndex.sources;
export const defaultAssessmentSourceId = assessmentIndex.defaultSourceId;
